const actionTypes = {
  SET_ANSWER: 'SET_ANSWER',
  SAVE_ANSWERS: 'SAVE_ANSWERS',
  RESET_ANSWERS: 'RESET_ANSWERS',
  VALIDATE_ANSWERS: 'VALIDATE_ANSWERS',
  VALIDATE_ANSWERS_SUCCESS: 'VALIDATE_ANSWERS_SUCCESS',
  VALIDATE_ANSWERS_FAILURE: 'VALIDATE_ANSWERS_FAILURE',
  FETCH_COMPLETED_ANSWERS: 'FETCH_COMPLETED_ANSWERS',
  FETCH_COMPLETED_ANSWERS_SUCCESS: 'FETCH_COMPLETED_ANSWERS_SUCCESS',
  FETCH_COMPLETED_ANSWERS_FAILURE: 'FETCH_COMPLETED_ANSWERS_FAILURE',
  SEND_ANSWERS: 'SEND_ANSWERS',
  SEND_ANSWERS_SUCCESS: 'SEND_ANSWERS_SUCCESS',
  SEND_ANSWERS_FAILURE: 'SEND_ANSWERS_FAILURE'
}

export default actionTypes;