const actionTypes = {
  SET_ANSWER: 'SET_ANSWER',
  SAVE_ANSWERS: 'SAVE_ANSWERS',
  RESET_ANSWERS: 'RESET_ANSWERS',
  VALIDATE_ANSWERS: 'VALIDATE_ANSWERS',
  VALIDATE_ANSWERS_SUCCESS: 'VALIDATE_ANSWERS_SUCCESS',
  VALIDATE_ANSWERS_FAILURE: 'VALIDATE_ANSWERS_FAILURE',

}

export default actionTypes;