const actionTypes = {
  REQUEST_QUESTIONS: 'REQUEST_QUESTIONS',
  FETCH_QUESTIONS_SUCCESS: 'FETCH_QUESTIONS_SUCCESS',
  FETCH_QUESTIONS_FAILURE: 'FETCH_QUESTIONS_FAILURE',

}
export default actionTypes;
