const actionTypes = {
  REGISTRATION_REQUEST: 'REGISTRATION_REQUEST',
  REGISTRATION_REQUEST_SUCCESS: 'REGISTRATION_REQUEST_SUCCESS',
  REGISTRATION_REQUEST_FAILURE: 'REGISTRATION_REQUEST_FAILURE'
}

export default actionTypes;