# Generated by Django 2.0.5 on 2018-11-13 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyFlowAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.IntegerField()),
                ('question', models.CharField(max_length=64)),
                ('category_name', models.CharField(max_length=32)),
                ('subcategory_name', models.CharField(max_length=32)),
                ('answer_text', models.CharField(max_length=16)),
                ('answer_score', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyLevelAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.IntegerField()),
                ('question', models.CharField(max_length=64)),
                ('category_name', models.CharField(max_length=32)),
                ('answer_text', models.CharField(max_length=16)),
                ('answer_score', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyMappingAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.IntegerField()),
                ('question', models.CharField(max_length=64)),
                ('category_name', models.CharField(max_length=32)),
                ('subcategory_name', models.CharField(max_length=32)),
                ('answer_text', models.CharField(max_length=16)),
                ('answer_score', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalityAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.IntegerField()),
                ('question', models.CharField(max_length=64)),
                ('category_name', models.CharField(max_length=32)),
                ('scale_alpha', models.IntegerField()),
                ('answer_text', models.CharField(max_length=16)),
                ('answer_score', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Profile')),
            ],
        ),
    ]
