# Generated by Django 2.0.5 on 2018-12-06 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question_ans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalityanswers',
            name='answer_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalityanswers',
            name='answer_last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='personalityanswers',
            name='category_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalityanswers',
            name='questionSign',
            field=models.CharField(default='null', max_length=16),
            preserve_default=False,
        ),
    ]
