# Generated by Django 2.0.5 on 2018-12-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_ans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalityanswers',
            old_name='questionId',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='personalityanswers',
            old_name='questionSign',
            new_name='question_sign',
        ),
    ]
