# Generated by Django 2.0.5 on 2018-12-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_ans', '0003_auto_20181209_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalityanswers',
            name='scale_alpha',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
