# Generated by Django 2.0.5 on 2018-12-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_ans', '0005_auto_20181209_1705'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personalityanswers',
            unique_together={('question_id', 'category_id')},
        ),
    ]
