# Generated by Django 2.0.5 on 2018-12-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_ans', '0006_auto_20181209_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalityanswers',
            name='question_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='personalityanswers',
            unique_together=set(),
        ),
    ]
