# Generated by Django 2.0.5 on 2018-12-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_ans', '0007_auto_20181209_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energymappinganswers',
            name='question',
            field=models.CharField(max_length=256),
        ),
    ]
