const actionTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  REQUEST_LOG_OUT: 'REQUEST_LOG_OUT',
  LOG_OUT: 'LOG_OUT',
}

export default actionTypes;