# Generated by Django 2.0.5 on 2018-11-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=32)),
                ('dob', models.CharField(max_length=16)),
                ('address', models.TextField()),
                ('job_title', models.CharField(max_length=64)),
                ('job_industry', models.CharField(max_length=64)),
                ('bio', models.TextField()),
                ('education', models.CharField(max_length=64)),
                ('user_img', models.URLField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('last_update', models.DateField(auto_now=True)),
                ('facebook_profile', models.URLField()),
                ('linkedIn_profile', models.URLField()),
                ('twitter_profile', models.URLField()),
                ('gitHub_profile', models.URLField()),
                ('instagram_profile', models.URLField()),
            ],
        ),
    ]
