# Generated by Django 2.0.5 on 2018-12-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20181206_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='address_city',
            field=models.CharField(default='n/a', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_country',
            field=models.CharField(default='n/a', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_postcode',
            field=models.CharField(default='n/a', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_street',
            field=models.CharField(default='n/a', max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(default='n/a', max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_industry',
            field=models.CharField(default='n/a', max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_title',
            field=models.CharField(default='n/a', max_length=64),
        ),
    ]
