# Generated by Django 2.0.5 on 2018-12-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20181207_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.CharField(default='n/a', max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(default='n/a', max_length=32),
        ),
    ]
