# Generated by Django 2.0.5 on 2018-12-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20181207_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_no',
            field=models.IntegerField(),
        ),
    ]
