# Generated by Django 2.0.5 on 2018-12-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20181207_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_no',
            field=models.IntegerField(default=1),
        ),
    ]
