# Generated by Django 2.0.5 on 2019-02-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_auto_20190221_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_city',
            field=models.CharField(default='n/a', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_country',
            field=models.CharField(default='n/a', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_no',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_postcode',
            field=models.CharField(default='n/a', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_street',
            field=models.CharField(default='n/a', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.CharField(default='n/a', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(default='n/a', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook_profile',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gitHub_profile',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_profile',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_industry',
            field=models.CharField(default='n/a', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_title',
            field=models.CharField(default='n/a', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_update',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedIn_profile',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='n/a', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(default='n/a', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_profile',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.TextField(default='', max_length=200, null=True),
        ),
    ]
